/**
 * generate-bundle.ts — checked-in generator for the Office Script port.
 *
 * Office Script *is* TypeScript, so we do NOT re-port the SheetCompressor core.
 * Instead we bundle the verified TS reference modules (the ones covered by the
 * 288-test suite) into a single `.osts` `namespace SheetCompressorInternal`,
 * byte-for-byte derived from the source. Only `main()` host glue and chart
 * extraction are hand-written.
 *
 * It emits three artifacts under `packages/officescript/src/`:
 *
 *   1. SheetCompressorInternal.generated.osts — the core namespace ONLY. This
 *      is the drift-guarded artifact (mirror of `prompts.test.ts`): the
 *      driftguard test re-runs this generator in memory and asserts the
 *      committed file matches byte-for-byte.
 *
 *   2. SheetCompressor.osts — the shippable script: a minimal
 *      `declare namespace ExcelScript` host-types block + the generated core
 *      namespace + a hand-written `main(workbook, sheetName?)` host glue.
 *
 *   3. conformance.osts — embeds every `fixtures/corpus/*` input + goldens as
 *      inlined literals, runs `SheetCompressorInternal.compress` over each, and
 *      prints a PASS/FAIL summary. A human pastes this into Excel Online to
 *      sign off (gate-style).
 *
 * The bundle must be ExcelScript-pure: no `node:*` imports, no `require`, no
 * `import.meta`. The gpt-tokenizer parts of `tokens.ts` are therefore excluded
 * (only `estimateTokens` + the `TokenCounter` type are inlined); `compress()`
 * defaults to `estimateTokens`, which is exactly what conformance uses.
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_DIR = resolve(__dirname, "..");
const REPO_ROOT = resolve(PKG_DIR, "..", "..");
const TS_SRC = join(REPO_ROOT, "packages", "typescript", "src");
const CORPUS_DIR = join(REPO_ROOT, "fixtures", "corpus");
const SRC_OUT = join(PKG_DIR, "src");

const GENERATED_CORE = join(SRC_OUT, "SheetCompressorInternal.generated.osts");
const SHIPPABLE = join(SRC_OUT, "SheetCompressor.osts");
const CONFORMANCE = join(SRC_OUT, "conformance.osts");

/** The core modules, in dependency order. */
const CORE_MODULES = [
  "types.ts",
  "address.ts",
  "encodings/escape.ts",
  "baseline.ts",
  "tokens.ts",
  "encodings/chartDescriptors.ts",
  "encodings/anchor.ts",
  "encodings/invertedIndex.ts",
  "encodings/formatAggregation.ts",
  "strategies.ts",
  "compress.ts",
] as const;

/**
 * Names from `tokens.ts` to DROP entirely (the gpt-tokenizer / node:module
 * surface). We keep only `estimateTokens` + the `TokenCounter` type (the latter
 * lives in types.ts). Everything here pulls in `createRequire`/`require`, which
 * ExcelScript does not have.
 */
const TOKENS_DROP = new Set([
  "TiktokenEncoding",
  "CreateTokenCounterOptions",
  "createTokenCounter",
  "GptTokenizerEncoding",
  "req",
  "loadGptTokenizerEncoding",
]);

const NS = "SheetCompressorInternal";
const HEADER =
  "// GENERATED by packages/officescript/scripts/generate-bundle.ts — DO NOT EDIT BY HAND.\n" +
  "// Source of truth: packages/typescript/src/ (the verified reference core).\n" +
  "// Regenerate with: npm run generate (in packages/officescript).\n";

type Decl = { name: string; module: string };

/**
 * Strip `import` / `import type` statements (single- and multi-line) from a
 * module body. Imports are how the TS source wires modules together; once we
 * concatenate everything into one namespace they're dead weight (and the
 * `node:*` / `./x.ts` specifiers are invalid in ExcelScript).
 */
function stripImports(src: string): string {
  // Remove multi-line `import ... from "...";` and `import "...";` blocks.
  // Imports in this codebase always terminate with `";` on some line.
  const lines = src.split("\n");
  const out: string[] = [];
  let inImport = false;
  for (const line of lines) {
    if (!inImport && /^\s*import\b/.test(line)) {
      // Single-line import?
      if (/;\s*$/.test(line) || /["']\s*;?\s*$/.test(line)) {
        if (/;\s*$/.test(line)) continue; // complete on one line
      }
      // Otherwise, it spans multiple lines until a line ending in `;`.
      if (/;\s*$/.test(line)) continue;
      inImport = true;
      continue;
    }
    if (inImport) {
      if (/;\s*$/.test(line)) inImport = false;
      continue;
    }
    out.push(line);
  }
  return out.join("\n");
}

/**
 * Drop the named top-level declarations (and their leading doc comments) from a
 * module body. Used to excise the gpt-tokenizer surface from `tokens.ts`.
 *
 * We work at the top-level brace/paren depth: a declaration starts at a line
 * matching `(export )?(function|const|type|class) <name>` at depth 0 and ends
 * when depth returns to 0 AND the statement is terminated.
 */
function dropDeclarations(src: string, drop: Set<string>): string {
  const lines = src.split("\n");
  const out: string[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!;
    const m = /^(?:export\s+)?(?:function|const|let|type|class|interface)\s+(\w+)/.exec(
      line,
    );
    if (m && drop.has(m[1]!)) {
      // Back up over any immediately-preceding doc comment / blank lines we
      // already pushed, so the dropped decl's comment goes with it.
      while (
        out.length > 0 &&
        (/^\s*\*/.test(out[out.length - 1]!) ||
          /^\s*\/\*/.test(out[out.length - 1]!) ||
          /^\s*\/\//.test(out[out.length - 1]!) ||
          out[out.length - 1]!.trim() === "")
      ) {
        // Only strip a contiguous comment block, not arbitrary earlier code.
        const prev = out[out.length - 1]!;
        if (prev.trim() === "" && out.length >= 2) {
          // keep a single separating blank but drop comment lines
        }
        if (/^\s*\*\/?/.test(prev) || /^\s*\/\*/.test(prev) || /^\s*\/\//.test(prev)) {
          out.pop();
        } else {
          break;
        }
      }
      // Consume the declaration by brace/paren balance.
      let depth = 0;
      let started = false;
      while (i < lines.length) {
        const l = lines[i]!;
        for (const ch of l) {
          if (ch === "{" || ch === "(" || ch === "[") {
            depth++;
            started = true;
          } else if (ch === "}" || ch === ")" || ch === "]") {
            depth--;
          }
        }
        i++;
        const trimmed = l.trimEnd();
        if (depth <= 0) {
          // Statement-style decl (e.g. `const X = /.../;` or `type X = ...;`)
          // ends at the first line terminating with `;`. Brace decls end when
          // depth returns to 0 on a line ending in `}`.
          if (started && /[};]\s*$/.test(trimmed)) break;
          if (!started && /;\s*$/.test(trimmed)) break;
          if (!started && /[}]\s*$/.test(trimmed)) break;
        }
      }
      continue;
    }
    out.push(line);
    i++;
  }
  return out.join("\n");
}

/**
 * Collect the names of top-level declarations in a module body (after import
 * stripping). Used for cross-file collision detection: inside one namespace,
 * two sibling decls with the same name would silently shadow.
 */
function collectTopLevelNames(src: string): string[] {
  const names: string[] = [];
  for (const line of src.split("\n")) {
    const m = /^(?:export\s+)?(?:function|const|let|var|type|class|interface)\s+(\w+)/.exec(
      line,
    );
    if (m) names.push(m[1]!);
  }
  return names;
}

/** Indent every non-empty line by two spaces (namespace body indentation). */
function indent(src: string): string {
  return src
    .split("\n")
    .map((l) => (l.length === 0 ? l : "  " + l))
    .join("\n");
}

/** Build the core namespace body from the TS source. */
function buildCoreNamespace(): string {
  const seen = new Map<string, string>(); // name -> module
  const bodies: string[] = [];

  for (const mod of CORE_MODULES) {
    const raw = readFileSync(join(TS_SRC, mod), "utf8");
    let body = stripImports(raw);
    if (mod === "tokens.ts") {
      body = dropDeclarations(body, TOKENS_DROP);
    }
    // Defensive: no stray node/require leaked through.
    if (/\b(require|createRequire|import\.meta|node:)\b/.test(body)) {
      throw new Error(
        `bundle: module ${mod} still contains node/require references after ` +
          `stripping — the ExcelScript bundle must be node-free.`,
      );
    }

    // Cross-file collision detection.
    for (const name of collectTopLevelNames(body)) {
      const prev = seen.get(name);
      if (prev !== undefined) {
        throw new Error(
          `bundle: name collision — '${name}' is declared in both ${prev} and ` +
            `${mod}. Two sibling declarations in one namespace would silently ` +
            `shadow; rename one in the TS source or special-case it here.`,
        );
      }
      seen.set(name, mod);
    }

    // Trim a leading file banner comment + leading/trailing blank lines so the
    // concatenation stays tidy, then re-wrap with a section marker.
    const trimmed = body.replace(/^\s*\n/, "").replace(/\n\s*$/, "");
    bodies.push(`// --- ${mod} ---\n${trimmed}`);
  }

  const joined = bodies.join("\n\n");
  return `namespace ${NS} {\n${indent(joined)}\n}\n`;
}

/** Minimal ExcelScript host-types block for the shippable script + tsc. */
function excelScriptTypes(): string {
  return `// Minimal ExcelScript host types. In Excel Online these are provided by the
// runtime; we declare just the surface main()/chart extraction touches so the
// generated .osts type-checks locally with NO node libs.
declare namespace ExcelScript {
  interface Range {
    getTexts(): string[][];
    getRowIndex(): number;
    getColumnIndex(): number;
    getAddressLocal?(): string;
  }
  interface ChartTitle {
    getText(): string;
  }
  interface Chart {
    getName(): string;
    getChartType(): ChartType;
    getTitle(): ChartTitle;
    getImage(): string;
  }
  interface Worksheet {
    getUsedRange(): Range | undefined;
    getCharts(): Chart[];
    getName(): string;
  }
  interface Workbook {
    getWorksheet(name: string): Worksheet | undefined;
    getActiveWorksheet(): Worksheet;
  }
  // The runtime ChartType enum is large; we only need it as an opaque string
  // tag for the type mapping in main(). Declaring it as a string keeps the
  // local typecheck free of the full enum while matching the runtime values
  // (the enum members serialize to these lowercase-ish identifiers).
  type ChartType = string;
}
`;
}

/** Hand-written host glue: reads the sheet, extracts charts, calls compress. */
function mainGlue(): string {
  return `// ---------------------------------------------------------------------------
// Host glue (hand-written — NOT generated). Maps the ExcelScript host model to
// the bundled SheetCompressorInternal core and back. Everything host-touching
// is defensive (try/catch) so a quirky workbook degrades rather than throws.
// ---------------------------------------------------------------------------

/**
 * Map an ExcelScript chart-type tag to the SPEC's 6-value ChartType. The
 * runtime enum has dozens of members (columnClustered, lineMarkers, pieExploded
 * …); we bucket by substring so new variants map sensibly, defaulting to
 * "other".
 */
function mapChartType(raw: string): ${NS}.ChartType {
  const t = (raw || "").toLowerCase();
  if (t.indexOf("bar") !== -1) return "bar";
  if (t.indexOf("column") !== -1) return "bar"; // column charts are bar-family
  if (t.indexOf("line") !== -1) return "line";
  if (t.indexOf("pie") !== -1 || t.indexOf("doughnut") !== -1) return "pie";
  if (t.indexOf("scatter") !== -1 || t.indexOf("xy") !== -1) return "scatter";
  if (t.indexOf("area") !== -1) return "area";
  return "other";
}

/**
 * Best-effort chart extraction from worksheet metadata → ChartDescriptor[].
 * Every host call is wrapped: a chart that throws on any accessor still yields
 * a partial descriptor rather than aborting the whole run. The optional base64
 * render (getImage) is intentionally NOT attached to the descriptor — it is not
 * part of the SPEC ChartDescriptor and would bloat the prompt. Flip
 * \`includeImage\` and read \`images\` if a caller wants it.
 */
function extractCharts(
  sheet: ExcelScript.Worksheet,
  includeImage: boolean,
): { charts: ${NS}.ChartDescriptor[]; images: { name: string; base64: string }[] } {
  const charts: ${NS}.ChartDescriptor[] = [];
  const images: { name: string; base64: string }[] = [];
  let hostCharts: ExcelScript.Chart[] = [];
  try {
    hostCharts = sheet.getCharts();
  } catch (e) {
    return { charts, images };
  }
  for (const chart of hostCharts) {
    let name = "";
    try {
      name = chart.getName();
    } catch (e) {
      name = "";
    }

    let type: ${NS}.ChartType = "other";
    try {
      type = mapChartType(String(chart.getChartType()));
    } catch (e) {
      type = "other";
    }

    // anchorRange is best-effort: the ExcelScript Chart surface does not expose
    // a clean anchor address, so we leave it empty when unavailable. The SPEC
    // treats anchorRange as opaque, so an empty string renders as CHART(type)@.
    let anchorRange = "";

    let title: string | undefined = undefined;
    try {
      const text = chart.getTitle().getText();
      if (text) title = text;
    } catch (e) {
      title = undefined;
    }

    const descriptor: ${NS}.ChartDescriptor = { name, type, anchorRange };
    if (title !== undefined) descriptor.title = title;
    charts.push(descriptor);

    if (includeImage) {
      try {
        const base64 = chart.getImage();
        if (base64) images.push({ name, base64 });
      } catch (e) {
        // image render is optional; ignore failures.
      }
    }
  }
  return { charts, images };
}

/**
 * Entry point for Excel Automate. Reads the target sheet's used range into a
 * Grid (origin from the range's 0-indexed row/col + 1), extracts chart
 * descriptors from host metadata, runs the bundled compress(), and returns all
 * three encodings (string + json + tokenEstimate) plus the chart echo and the
 * raw baseline. Pass \`includeImage = true\` to also return base64 chart renders.
 */
function main(
  workbook: ExcelScript.Workbook,
  sheetName?: string,
  includeImage: boolean = false,
): {
  sheetName: string;
  origin: { row: number; col: number };
  encodings: {
    anchor: { string: string; json: string; tokenEstimate: number };
    invertedIndex: { string: string; json: string; tokenEstimate: number };
    formatAggregation: { string: string; json: string; tokenEstimate: number };
  };
  charts: ${NS}.ChartDescriptor[];
  rawBaseline: { tokenEstimate: number };
  images: { name: string; base64: string }[];
} {
  const sheet = sheetName
    ? workbook.getWorksheet(sheetName)
    : workbook.getActiveWorksheet();
  if (!sheet) throw new Error("Worksheet not found: " + (sheetName ?? "(active)"));

  const range = sheet.getUsedRange();
  // An empty sheet has no used range; treat as an empty grid at A1.
  const texts: string[][] = range ? range.getTexts() : [];
  const origin = {
    row: (range ? range.getRowIndex() : 0) + 1,
    col: (range ? range.getColumnIndex() : 0) + 1,
  };

  const extracted = extractCharts(sheet, includeImage);

  // Charts ride on the Grid (SPEC §1); compress() reads them from there and
  // appends the CHART(...) tokens + echoes them on result.charts (SPEC §6).
  const grid: ${NS}.Grid = {
    rows: texts,
    origin,
    charts: extracted.charts,
  };

  const result = ${NS}.compress(grid);

  const enc = (e: ${NS}.Encoding<unknown>) => ({
    string: e.string,
    json: JSON.stringify(e.json, null, 2) + "\\n",
    tokenEstimate: e.tokenEstimate,
  });

  return {
    sheetName: sheet.getName(),
    origin,
    encodings: {
      anchor: enc(result.encodings.anchor),
      invertedIndex: enc(result.encodings.invertedIndex),
      formatAggregation: enc(result.encodings.formatAggregation),
    },
    charts: result.charts,
    rawBaseline: result.rawBaseline,
    images: extracted.images,
  };
}
`;
}

type Fixture = {
  id: string;
  input: unknown;
  anchorString: string;
  anchorJson: string;
  invertedString: string;
  invertedJson: string;
  formatString: string;
  formatJson: string;
  chartsJson: string;
};

function loadFixtures(): Fixture[] {
  const ids = readdirSync(CORPUS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  const fixtures: Fixture[] = [];
  for (const id of ids) {
    const g = join(CORPUS_DIR, id, "golden");
    const read = (f: string) => readFileSync(join(g, f), "utf8");
    fixtures.push({
      id,
      input: JSON.parse(readFileSync(join(CORPUS_DIR, id, "input.json"), "utf8")),
      anchorString: read("anchor.string.txt"),
      anchorJson: read("anchor.json"),
      invertedString: read("invertedIndex.string.txt"),
      invertedJson: read("invertedIndex.json"),
      formatString: read("formatAggregation.string.txt"),
      formatJson: read("formatAggregation.json"),
      chartsJson: read("charts.json"),
    });
  }
  return fixtures;
}

/** The embedded-fixture literal block shared by conformance.osts. */
function buildFixturesLiteral(fixtures: Fixture[]): string {
  // Emit as a JSON.parse of one big literal — compact, exact, and trivially
  // diffable by the drift guard. JSON.stringify with no indent keeps it on one
  // line per fixture-ish; we pretty-print 2-space for readability + stable diff.
  const payload = fixtures.map((f) => ({
    id: f.id,
    input: f.input,
    anchorString: f.anchorString,
    anchorJson: f.anchorJson,
    invertedString: f.invertedString,
    invertedJson: f.invertedJson,
    formatString: f.formatString,
    formatJson: f.formatJson,
    chartsJson: f.chartsJson,
  }));
  return JSON.stringify(payload, null, 2);
}

function buildConformance(fixtures: Fixture[], coreNamespace: string): string {
  const literal = buildFixturesLiteral(fixtures);
  return `${HEADER}
// The Automate entry point receives a Workbook even when the script ignores it,
// so we declare the minimal surface for a local typecheck.
declare namespace ExcelScript {
  interface Workbook {}
}

${coreNamespace}
// ---------------------------------------------------------------------------
// In-host conformance harness. Paste into Excel Online Automate and run; it
// needs no workbook data — every fixture input + golden is embedded below,
// regenerated from fixtures/corpus/ by generate-bundle.ts. It runs the bundled
// compress() over each fixture and diffs the string + JSON forms byte-for-byte,
// printing a PASS/FAIL summary. A human runs this to sign off (issue #18).
// ---------------------------------------------------------------------------

type EmbeddedFixture = {
  id: string;
  input: ${NS}.Grid;
  anchorString: string;
  anchorJson: string;
  invertedString: string;
  invertedJson: string;
  formatString: string;
  formatJson: string;
  chartsJson: string;
};

const EMBEDDED_FIXTURES: EmbeddedFixture[] = JSON.parse(
  ${JSON.stringify(literal)}
) as EmbeddedFixture[];

function jsonGolden(value: unknown): string {
  // Goldens are 2-space-indented with a trailing newline (SPEC §3.3).
  return JSON.stringify(value, null, 2) + "\\n";
}

function main(_workbook: ExcelScript.Workbook): void {
  let pass = 0;
  let fail = 0;
  let firstMismatch = "";
  const failedIds: string[] = [];

  for (const fx of EMBEDDED_FIXTURES) {
    const result = ${NS}.compress(fx.input);
    const checks: { label: string; got: string; want: string }[] = [
      { label: "anchor.string", got: result.encodings.anchor.string, want: fx.anchorString },
      { label: "anchor.json", got: jsonGolden(result.encodings.anchor.json), want: fx.anchorJson },
      { label: "invertedIndex.string", got: result.encodings.invertedIndex.string, want: fx.invertedString },
      { label: "invertedIndex.json", got: jsonGolden(result.encodings.invertedIndex.json), want: fx.invertedJson },
      { label: "formatAggregation.string", got: result.encodings.formatAggregation.string, want: fx.formatString },
      { label: "formatAggregation.json", got: jsonGolden(result.encodings.formatAggregation.json), want: fx.formatJson },
      { label: "charts.json", got: jsonGolden(result.charts), want: fx.chartsJson },
    ];
    let ok = true;
    for (const c of checks) {
      if (c.got !== c.want) {
        ok = false;
        if (firstMismatch === "") {
          firstMismatch =
            fx.id + " / " + c.label + "\\n  want: " + JSON.stringify(c.want) +
            "\\n  got:  " + JSON.stringify(c.got);
        }
      }
    }
    if (ok) {
      pass++;
    } else {
      fail++;
      // Collect failures and report once after the loop — logging inside the
      // loop trips the Office Scripts "console.log in a loop" performance lint.
      failedIds.push(fx.id);
    }
  }

  console.log("=== SheetCompressor conformance ===");
  console.log("PASS " + pass + " / " + (pass + fail) + " fixtures");
  if (fail > 0) {
    console.log("FAIL " + fail + " fixtures: " + failedIds.join(", "));
    console.log("First mismatch:\\n" + firstMismatch);
  } else {
    console.log("All fixtures byte-identical to goldens.");
  }
}
`;
}

function buildShippable(coreNamespace: string): string {
  return `${HEADER}
${excelScriptTypes()}
${coreNamespace}
${mainGlue()}`;
}

/**
 * Build all three artifacts in memory (the single source of truth shared by the
 * CLI `main()` and the drift-guard test). Returns the exact bytes that should be
 * on disk.
 */
function buildArtifacts(): {
  generatedCore: string;
  shippable: string;
  conformance: string;
  fixtureCount: number;
} {
  const coreNamespace = buildCoreNamespace();
  const fixtures = loadFixtures();
  return {
    generatedCore: `${HEADER}\n${coreNamespace}`,
    shippable: buildShippable(coreNamespace),
    conformance: buildConformance(fixtures, coreNamespace),
    fixtureCount: fixtures.length,
  };
}

const ARTIFACT_PATHS = {
  generatedCore: GENERATED_CORE,
  shippable: SHIPPABLE,
  conformance: CONFORMANCE,
} as const;

function main(): void {
  const { generatedCore, shippable, conformance, fixtureCount } =
    buildArtifacts();

  writeFileSync(GENERATED_CORE, generatedCore);
  writeFileSync(SHIPPABLE, shippable);
  writeFileSync(CONFORMANCE, conformance);

  console.log(`Wrote ${GENERATED_CORE}`);
  console.log(`Wrote ${SHIPPABLE}`);
  console.log(`Wrote ${CONFORMANCE} (${fixtureCount} fixtures embedded)`);
}

// Exposed for the drift-guard test (in-memory regeneration).
export {
  buildArtifacts,
  ARTIFACT_PATHS,
  buildCoreNamespace,
  buildShippable,
  buildConformance,
  loadFixtures,
  HEADER,
};

const isMain =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isMain) main();
